---
title: "omniscape inputs"
output: html_document
date: '2022-10-05'
---

## Running Biophysical Omniscape Models:

In order to produce the biophysical connectivity models, we will use an external software called Julia 1.7 to implement Omniscape. We must prep an .ini file as well as obtain a source and resistance input for each model.

Source input: bbear habitat suitability.tif

Resistance input: agnostic_biophys_resist.tif

.ini file format: we use a text editor to produce an .ini file with the information below:

NOTE: Block size and radius must be selected. Typically, radius is derived from the home range area of an individual in the species of interest. Block size must be an odd number, but is typically selected to be about 1/10 of the radius (Phillips et al., 2021; McClure et al., 2016).

We use an "average" home range size across gender for black bears to inform our models.

##MALE black bear .ini inputs:
[Required]
resistance_file = forest_sp_biophys_resist.tif
project_name = Black Bear Biophys

[Options]
radius = 6.3 # average home range for black bears is typically around 125 km^2, +/- 30 km
block_size = 0.6 # this is 1/10 the block size
source_threshold = 0
source_from_resistance = false
source_file = bbear_habitat_suitability.tif

r_cutoff = 50
precision = double
solver = cholmod
calc_normalized_current = true
calc_flow_potential = true
mask_nodata = true
parallelize = true
parallel_batch_size = 20

[Output options]
write_raw_currmap = true
write_as_tif = true

